# Site wide configuration

title: Nerdyminion
description: "Stephen Salinas"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //nerdyminion.com

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Stephen Salinas
  web: http://nerdyminion.com
  email: shsalinas2012@gmail.com
  twitter: shsalinas2012
  bio: "MIT materials scientst turned infrastructure engineer"
  avatar: minion-square.png


exclude:
  - lib
  - config.rb
  - .sass-cache
  - Capfile
  - config
  - log
  - Rakefile
  - Rakefile.rb
  - tmp
  - '*.sublime-project'
  - '*.sublime-workspace'
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - Gruntfile.js
  - package.json
